apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: observer
  labels:
    io.kompose.service: api
  name: api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  - port: 4001
    targetPort: 4001
  - port: 6666
    targetPort: 6666
    protocol: TCP
  selector:
    io.kompose.service: api
