apiVersion: v1
kind: Service
metadata:
  namespace: observer
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: "4001"
    port: 4001
    targetPort: 4001
  selector:
    io.kompose.service: api
