apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: observer
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - observer.rubyforce.co
    secretName: observer-tls
  rules:
  - host: observer.rubyforce.co
    http:
      paths:
      - path: /api
        backend:
          serviceName: api
          servicePort: http
