version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    container_name: observer_elasticsearch
    ports:
      - 9200
    networks:
      - back-tier
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  redis:
    image: redis:alpine
    container_name: observer_redis
    ports:
      - 6379
    networks:
      - back-tier

  api:
    build: ./
    volumes:
      - ./:/app
    dns:
      - "8.8.8.8"
    networks:
      - back-tier
    ports:
      - "127.0.0.1:8080:8080"
    tty: true
    depends_on:
      - redis
      - elasticsearch
    links:
      - redis
      - elasticsearch
    command: /bin/sh make.sh server

  simulate:
    build: ./
    volumes:
      - ./:/app
    environment:
      TCP_HOST: api
    dns:
      - "8.8.8.8"
    networks:
      - back-tier
    depends_on:
      - api
    tty: true
    links:
      - api
    command: /bin/sh make.sh simulate

  web:
    build: ./web/
    volumes:
      - ./web:/app
    dns:
      - "8.8.8.8"
    networks:
      - back-tier
    depends_on:
      - api
    tty: true
    ports:
      - "127.0.0.1:4200:4200"
      - "127.0.0.1:49153:49153"
    links:
      - api
    command: /bin/ash -c "yarn && ./node_modules/.bin/ember s"

volumes:
  db-data:

networks:
  back-tier:
