apiVersion: v1
kind: Service
metadata:
  namespace: observer
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    io.kompose.service: web
