apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: observer
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: observer-web-nginx
          image: "nginx"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: web-app
              readOnly: true
        - name: observer-web
          image: docker-registry.rubyforce.co:5000/observer/observer_web:0.0.1
          name: web
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /app
              name: web-app
      restartPolicy: Always
      volumes:
        - name: web-app
          emptyDir: {}
