apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  - name: "49153"
    port: 49153
    targetPort: 49153
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
