apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: Opaque
data:
  docker-server: ZG9ja2VyLXJlZ2lzdHJ5LnJ1Ynlmb3JjZS5jbzo1MDAwCg==
  docker-username: b2l2b29kb28K
  docker-password: MjAxMjg3YWxpCg==
  docker-email: YWxleC5rb3JzYWtAZ21haWwuY29tCg==
