apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "4000"
    port: 4000
    targetPort: 4000
  - name: "4001"
    port: 4001
    targetPort: 4001
  - name: "4002"
    port: 4002
    targetPort: 4002
  - name: "6666"
    port: 6666
    targetPort: 6666
  - name: "6667"
    port: 6667
    targetPort: 6667
  - name: "6668"
    port: 6668
    targetPort: 6668
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
